# Generated by Django 5.0.1 on 2025-08-07 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHaberler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haber_baslik', models.CharField(max_length=255)),
                ('haber_link', models.URLField()),
                ('haber_kaynak', models.CharField(blank=True, max_length=100, null=True)),
                ('haber_tarih', models.CharField(blank=True, max_length=100, null=True)),
                ('haber_resim', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
